<?php

namespace Ksp\ScienceBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BiomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Biome extends EntityRepository
{
}
